name: "Upload coverage reports"
description: "This action uploads coverage reports for the different flags"
inputs:
  codecov-token:
    description: 'Codecov token'
    required: true
  codecov-flag:
    description: 'Codecov flag'
    required: true
  coverage-files:
    description: 'Coverage files'
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate combined coverage report from files
      run: |
        echo "Combining coverage files: ${{ inputs.coverage-files }}"
        coverage combine --keep ${{ inputs.coverage-files }}
      shell: bash

    - name: Upload ${{ inputs.codecov-flag }} tests coverage report to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ inputs.codecov-token }}
      with:
        files: .coverage  # Here for some reason, we need to have .coverage as a filename
        flags: ${{ inputs.codecov-flag }}_tests
        name: ${{ inputs.codecov-flag }}_tests
